### ISSUE TITLE
Bug: problem with package's depedency "@kinde-oss/kinde-auth-pkce-js".

### ISSUE THREAD

**Issue by DiarFonda** [kinde-oss/kinde-auth-react#40] opened 2024-02-04 09:29 UTC
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

error:  unhandledRejection: Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/@kinde-oss/kinde-auth-pkce-js/dist/kinde-auth-pkce-js.umd.min.js from node_modules/@kinde-oss/kinde-auth-react/dist/kinde-auth-react.umd.min.js not supported. kinde-auth-pkce-js.umd.min.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename kinde-auth-pkce-js.umd.min.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/diar_personal/dashboard/node_modules/@kinde-oss/kinde-auth-pkce-js/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

### Library URL

"https://github.com/kinde-oss/kinde-auth-react"

### Library version

"^3.0.21"

### Operating system(s)

Ubuntu

### Operating system version(s)

Ubuntu 20.04

**Comment by DaveOrDead** [comment] 2024-02-05 11:27
Hey @DiarFonda thanks for raising this one :) 

I haven't been able to reproduce the issue, is there anything else you can tell me about your setup which could help me to reproduce it?

**Comment by ThatOneAwkwardGuy** [comment] 2024-02-10 19:42
I believe the issue is that the library is ESM only, and doesn't support commonJS. although the [kinde-typescript-sdk](https://github.com/kinde-oss/kinde-typescript-sdk/tree/main) package seems to support both.

**Comment by DaveOrDead** [comment] 2024-02-15 05:12
@ThatOneAwkwardGuy Interesting, I thought it supported both. I don't think it would be a huge effort to update the bundler to export a commonjs version

**Comment by rkacenski** [comment] 2024-02-27 19:24
Currently copying and pasting the provider into my project... will this be fixed?

**Comment by atifcppprogrammer** [comment] 2024-03-01 11:09
@DaveOrDead please assign this to me, since I intend to work on an [issue](https://github.com/kinde-oss/kinde-auth-pkce-js/issues/32) in the same upstream package this weekend. :+1:. I'll take a look at this too.

**Comment by xamthor** [comment] 2024-03-24 06:24
I am running into the same issue, any update on the fix ? 

using nextjs 

```
"@kinde-oss/kinde-auth-react": "^3.0.28",
"axios": "^1.6.8",
"next": "14.1.3",
"react": "^18",
"react-dom": "^18"
```

**Comment by ikx94** [comment] 2024-04-22 13:24
I can't get Kinde to work because of this issue. @atifcppprogrammer if you could please look at it, that would be great.

**Comment by atifcppprogrammer** [comment] 2024-04-22 13:33
Oh hey @ikx94 ! my apologies. I was assigned this a while ago and I totally forgot. I'll get this patched today or tomorrow at the very latest.

**Comment by ikx94** [comment] 2024-04-22 14:23
> Oh hey @ikx94 ! my apologies. I was assigned this a while ago and I totally forgot about it. I'll get this patched today or tomorrow at the very latest.

Thank you. The same thing happens with the Node/Express package, it happens both client and server side, I think because they use the same common library that's causing this.

Thank you for looking into it.

**Comment by atifcppprogrammer** [comment] 2024-04-25 16:11
Hi @ikx94, can you be a little more specific with regards to what packages you are referring to the "Node/Express package".

**Closed** 2024-04-25 16:47 UTC
Labels: bug
